package com.workmotion.statemachine;

public enum EmployeeState {

	ADDED,
	IN_CHECK,APPROVED,ACTIVE,SECURITY_CHECK_STARTED,
	SECURITY_CHECK_FINISHED,WORK_PERMIT_CHECK_STARTED
	,WORK_PERMIT_CHECK_PENDING_VERIFICATION
	,WORK_PERMIT_CHECK_FINISHED,
	
	ALL_CHECK_FINISHED
	
}
